"""Generate the migration & lineage report (Markdown + JSON).

The report is the deliverable a migration lead uses to scope, estimate and
sign off the conversion: object inventory, field-level lineage, and an explicit
list of everything that needs manual review.
"""
from __future__ import annotations

import json

from ..models import QvScript
from .dbt_models import ModelFile


def _model_index(models: list[ModelFile]) -> dict[str, ModelFile]:
    return {m.name: m for m in models}


def build(script: QvScript, models: list[ModelFile], config: dict):
    total_fields = sum(len(t.fields) for t in script.tables)
    flagged_fields = sum(1 for t in script.tables for f in t.fields if f.warnings)
    review_items = [w for m in models for w in m.warnings]

    summary = {
        "script": script.name,
        "tables": len(script.tables),
        "models_generated": len(models),
        "mapping_tables": len(script.maps),
        "external_sources": len(script.sources),
        "variables": len(script.variables),
        "total_fields": total_fields,
        "fields_needing_review": flagged_fields,
        "auto_translatable_pct": round(
            100 * (total_fields - flagged_fields) / total_fields, 1
        ) if total_fields else 100.0,
        "unsupported_statements": len(script.unsupported),
    }

    data = {
        "summary": summary,
        "layers": {
            layer: [t.name for t in script.tables if t.layer == layer]
            for layer in ("staging", "intermediate", "mart")
        },
        "tables": [
            {
                "name": t.name,
                "layer": t.layer,
                "load_kind": t.kind.value,
                "source": t.source if t.kind.value != "sql" else "<SQL SELECT>",
                "fields": len(t.fields),
                "joins": [j.right_table for j in t.joins],
                "warnings": t.warnings,
            }
            for t in script.tables
        ],
        "lineage": [
            {
                "target": f"{t.name}.{f.alias}",
                "expression": f.source_expr,
                "snowflake": f.sf_expr,
                "review": f.warnings,
            }
            for t in script.tables for f in t.fields
        ],
        "sources": [
            {"name": s.identifier, "kind": s.kind.value, "locator": s.locator}
            for s in script.sources
        ],
        "unsupported": script.unsupported,
        "dropped_tables": script.dropped_tables,
    }

    return _render_markdown(script, models, data), data


def _render_markdown(script, models, data) -> str:
    s = data["summary"]
    idx = _model_index(models)
    L: list[str] = []
    L.append(f"# QlikView -> dbt / Snowflake Migration Report")
    L.append(f"\n**Source script:** `{script.name}`  ")
    L.append(f"**Generated by:** qv2dbt accelerator\n")

    L.append("## 1. Summary\n")
    L.append("| Metric | Value |")
    L.append("|---|---|")
    L.append(f"| QlikView tables | {s['tables']} |")
    L.append(f"| dbt models generated | {s['models_generated']} |")
    L.append(f"| Mapping tables | {s['mapping_tables']} |")
    L.append(f"| External sources (QVD/file/SQL) | {s['external_sources']} |")
    L.append(f"| Script variables | {s['variables']} |")
    L.append(f"| Total fields | {s['total_fields']} |")
    L.append(f"| Fields needing review | {s['fields_needing_review']} |")
    L.append(f"| **Auto-translatable** | **{s['auto_translatable_pct']}%** |")
    L.append(f"| Unsupported statements | {s['unsupported_statements']} |")

    L.append("\n## 2. dbt Layer Assignment\n")
    for layer in ("staging", "intermediate", "mart"):
        names = data["layers"][layer]
        L.append(f"**{layer}** ({len(names)}): "
                 + (", ".join(f"`{n}`" for n in names) or "_none_"))

    L.append("\n## 3. Table Inventory\n")
    L.append("| QlikView table | Layer | Load kind | Source | Fields | Joins | Review |")
    L.append("|---|---|---|---|---|---|---|")
    for t in data["tables"]:
        src = (t["source"] or "-")
        src = (src[:40] + "...") if len(src) > 43 else src
        L.append(f"| {t['name']} | {t['layer']} | {t['load_kind']} | "
                 f"`{src}` | {t['fields']} | {', '.join(t['joins']) or '-'} | "
                 f"{len(t['warnings'])} |")

    L.append("\n## 4. Field-Level Lineage\n")
    L.append("QlikView expression -> Snowflake SQL (per target field).\n")
    for t in script.tables:
        if not t.fields:
            continue
        L.append(f"\n### {t.name}\n")
        L.append("| Target field | QlikView expression | Snowflake SQL | Review |")
        L.append("|---|---|---|---|")
        for f in t.fields:
            qv = f.source_expr.replace("|", "\\|")
            sf = (f.sf_expr or "").replace("|", "\\|")
            flag = "yes" if f.warnings else ""
            L.append(f"| {f.alias} | `{qv[:60]}` | `{sf[:60]}` | {flag} |")

    L.append("\n## 5. Items Requiring Manual Review\n")
    review = [(t.name, f.alias, w) for t in script.tables
              for f in t.fields for w in f.warnings]
    if review:
        L.append("| Table | Field | Note |")
        L.append("|---|---|---|")
        for tbl, fld, w in review:
            L.append(f"| {tbl} | {fld} | {w} |")
    else:
        L.append("_None - all expressions auto-translated._")

    L.append("\n## 6. Unsupported / Manually-Handled Statements\n")
    if data["unsupported"]:
        L.append("These QlikView statements have no direct dbt equivalent and "
                 "were recorded for manual handling (control flow, STORE, "
                 "RENAME, DROP):\n")
        L.append("| Kind | Statement (truncated) |")
        L.append("|---|---|")
        for u in data["unsupported"]:
            raw = u["raw"].replace("|", "\\|").replace("\n", " ")
            L.append(f"| {u['kind']} | `{raw[:80]}` |")
    else:
        L.append("_None._")
    if data["dropped_tables"]:
        L.append(f"\n**Dropped tables (QlikView DROP):** "
                 + ", ".join(data["dropped_tables"]))

    L.append("\n## 7. Construct Mapping Legend\n")
    L.append("| QlikView | dbt / Snowflake target |")
    L.append("|---|---|")
    for a, b in [
        ("`LOAD ... FROM x.qvd`", "staging model + `source()` + RAW DDL"),
        ("`LOAD ... RESIDENT`", "intermediate model + `ref()`"),
        ("`LEFT/INNER JOIN`", "SQL `JOIN ... USING(common cols)`"),
        ("`CONCATENATE`", "`UNION ALL`"),
        ("`MAPPING LOAD` + `ApplyMap()`", "mapping model + `apply_map()` macro"),
        ("`if()/Date()/Num()/&`", "`CASE`/`TO_DATE`/`TO_NUMBER`/`||`"),
        ("`STORE/DROP/RENAME`", "handled by dbt materialization (not migrated)"),
    ]:
        L.append(f"| {a} | {b} |")

    return "\n".join(L) + "\n"
