-- ================================================================
-- Snowflake views generated by qv2dbt from sales_pipeline.qvs
-- Run top-to-bottom (already in dependency order).
-- ================================================================
create schema if not exists LUNDBECK_UKIE.STAGING;
create schema if not exists LUNDBECK_UKIE.MARTS;

-- Products  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_PRODUCTS as
select
    ProductID,
    ProductName,
    "Therapeutic Area" as THERAPEUTICAREA,
    TO_NUMBER(UnitPrice) as UNITPRICE,
    CASE WHEN Discontinued = 1 THEN 'Y' ELSE 'N' END as ISDISCONTINUED
from LUNDBECK_UKIE.RAW.PRODUCTS as base
;

-- SalesRaw  [intermediate]  (from QlikView 'file')
create or replace view LUNDBECK_UKIE.STAGING.INT_SALES_RAW as
select
    OrderID,
    ProductID,
    CustomerID,
    CountryCode,
    TO_DATE(OrderDate, 'YYYY-MM-DD') as ORDERDATE,
    TO_NUMBER(Quantity) as QUANTITY,
    TO_NUMBER(UnitPrice) * TO_NUMBER(Quantity) as GROSSAMOUNT,
    coalesce((select MAPPED_VALUE from LUNDBECK_UKIE.STAGING.MAP_COUNTRY_MAP where MAPPED_KEY = CountryCode limit 1), 'Unknown') as COUNTRY,
    LEFT(OrderID, 4) as ORDERPREFIX
from LUNDBECK_UKIE.RAW.SALES_2026 as base
union all
select * from LUNDBECK_UKIE.STAGING.INT_SALES_RAW_JOIN4
where LENGTH(OrderID) > 0
;

-- SalesPY  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_SALES_PY as
select
    OrderID,
    ProductID,
    CustomerID,
    CountryCode,
    TO_DATE(OrderDate, 'YYYY-MM-DD') as ORDERDATE,
    TO_NUMBER(Quantity) as QUANTITY,
    TO_NUMBER(GrossAmount) as GROSSAMOUNT
from LUNDBECK_UKIE.RAW.SALES_2025 as base
;

-- SalesRaw__join4  [intermediate]  (from QlikView 'resident')
create or replace view LUNDBECK_UKIE.STAGING.INT_SALES_RAW_JOIN4 as
select
    *
from LUNDBECK_UKIE.STAGING.STG_SALES_PY as base
;

-- SalesEnriched  [intermediate]  (from QlikView 'resident')
create or replace view LUNDBECK_UKIE.STAGING.INT_SALES_ENRICHED as
select *
from (select 
    OrderID,
    ProductID,
    CustomerID,
    Country,
    OrderDate,
    Quantity,
    GrossAmount
from LUNDBECK_UKIE.STAGING.INT_SALES_RAW) as base
left join LUNDBECK_UKIE.STAGING.INT_SALES_ENRICHED_JOIN6 as j1 using (PRODUCTID)
;

-- SalesEnriched__join6  [intermediate]  (from QlikView 'resident')
create or replace view LUNDBECK_UKIE.STAGING.INT_SALES_ENRICHED_JOIN6 as
select
    ProductID,
    ProductName,
    TherapeuticArea
from LUNDBECK_UKIE.STAGING.STG_PRODUCTS as base
;

-- sales_fact  [mart]  (from QlikView 'resident')
create or replace view LUNDBECK_UKIE.MARTS.MART_SALES_FACT as
select
    ProductID,
    Country,
    TherapeuticArea,
    YEAR(OrderDate) as ORDERYEAR,
    SUM(GrossAmount) as TOTALREVENUE,
    SUM(Quantity) as TOTALUNITS
from LUNDBECK_UKIE.STAGING.INT_SALES_ENRICHED as base
group by ProductID, Country, TherapeuticArea, YEAR(OrderDate)
;

