-- =====================================================================
-- Snowflake RAW landing DDL  (generated by qv2dbt from executive_dashboard.qvs)
-- Types are inferred heuristically - review against source metadata.
-- =====================================================================
CREATE DATABASE IF NOT EXISTS LUNDBECK_UKIE;
CREATE SCHEMA IF NOT EXISTS LUNDBECK_UKIE.RAW;

-- Source: lib://Executive Dashboard:DataFiles/AccountGroupMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.ACCOUNTGROUPMASTER (
    ACCOUNTGROUP                             VARCHAR(16777216),
    ACCOUNTGROUPDESC                         VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/AccountMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.ACCOUNTMASTER (
    ACCOUNT                                  VARCHAR(16777216),
    ACCOUNTGROUP                             VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/Accounts.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.ACCOUNTS (
    ACCOUNT                                  VARCHAR(16777216),
    ACCOUNTDESC                              VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/ARSummary-1.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.ARSUMMARY_1 (
    CUSTKEYAR                                VARCHAR(16777216),
    ARAGE                                    VARCHAR(16777216),
    ARAGEBAL                                 VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/ARSummary.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.ARSUMMARY (
    CUSTKEYAR                                VARCHAR(16777216),
    ARGROSS                                  VARCHAR(16777216),
    AROPEN                                   VARCHAR(16777216),
    ARCURRENT                                VARCHAR(16777216),
    AR1-30                                   VARCHAR(16777216),
    AR31-60                                  VARCHAR(16777216),
    AR60+                                    VARCHAR(16777216),
    ARCREDIT                                 VARCHAR(16777216),
    ARSALESPERDAY                            NUMBER(38,4),
    ARAVGBAL                                 VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/Budget.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.BUDGET (
    MONTHLYREGIONKEY                         VARCHAR(16777216),
    BUDGET AMOUNT                            NUMBER(38,4)
);

-- Source: lib://DataFiles/Calendar_2024.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.CALENDAR_2024 (
    FISCAL QUARTER                           VARCHAR(16777216),
    FISCALMONTHNUM                           VARCHAR(16777216),
    FISCAL YEAR                              VARCHAR(16777216),
    FISCALMONTH                              VARCHAR(16777216),
    FISCALROLLQT                             VARCHAR(16777216),
    YYYYMM                                   VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/ChannelMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.CHANNELMASTER (
    SEGMENT                                  VARCHAR(16777216),
    SEGMENTDESC                              VARCHAR(16777216),
    SEGMENTGROUP                             VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/CustomerAddressMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.CUSTOMERADDRESSMASTER (
    ADDRESS NUMBER                           VARCHAR(16777216),
    CUSTOMER ADDRESS 1                       VARCHAR(16777216),
    ZIP CODE                                 VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/CustomerMap.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.CUSTOMERMAP (
    CUSTKEY                                  VARCHAR(16777216),
    CUSTKEYAR                                VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/CustomerMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.CUSTOMERMASTER (
    ADDRESS NUMBER                           VARCHAR(16777216),
    BUSINESS FAMILY                          VARCHAR(16777216),
    SEGMENT                                  VARCHAR(16777216),
    CUSTOMER                                 VARCHAR(16777216),
    CUSTOMER NUMBER                          VARCHAR(16777216),
    CUSTOMER TYPE                            VARCHAR(16777216),
    DISTRIBUTION CHANNEL MGR                 VARCHAR(16777216),
    DIVISION                                 VARCHAR(16777216),
    PHONE                                    VARCHAR(16777216),
    REGION CODE                              VARCHAR(16777216),
    REGIONAL SALES MGR                       NUMBER(38,4),
    ZONE MGR                                 VARCHAR(16777216),
    SALES REP                                NUMBER(38,4)
);

-- Source: lib://Executive Dashboard:DataFiles/Expenses.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.EXPENSES (
    MONTHLYREGIONKEY                         VARCHAR(16777216),
    ACCOUNT                                  VARCHAR(16777216),
    EXPENSEACTUAL                            VARCHAR(16777216),
    EXPENSEBUDGET                            VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/FactTable.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.FACTTABLE (
    MONTHLYREGIONKEY                         VARCHAR(16777216),
    REGION                                   VARCHAR(16777216),
    ADDRESS NUMBER                           VARCHAR(16777216),
    CUSTKEY                                  VARCHAR(16777216),
    INVOICE NUMBER                           VARCHAR(16777216),
    ITEM-BRANCH KEY                          VARCHAR(16777216),
    LATE SHIPMENT                            VARCHAR(16777216),
    LINE DESC 1                              VARCHAR(16777216),
    OPEN ORDER AMOUNT                        NUMBER(38,4),
    ORDER NUMBER                             VARCHAR(16777216),
    ORDER STATUS                             VARCHAR(16777216),
    ORDERDATE                                DATE,
    ORDERID                                  VARCHAR(100),
    ORDERSTAT                                VARCHAR(16777216),
    PROMISED DELIVERY DATE                   DATE,
    SALES AMOUNT                             NUMBER(38,4),
    SALES COST AMOUNT                        NUMBER(38,4),
    SALES MARGIN AMOUNT                      NUMBER(38,4),
    SALES PRICE                              NUMBER(38,4),
    SALES QUANTITY                           NUMBER(38,4),
    SHIP TO                                  VARCHAR(16777216),
    YYYYMM                                   VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/HistoryFlag.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.HISTORYFLAG (
    YYYYMM                                   VARCHAR(16777216),
    _HISTORYFLAG                             BOOLEAN
);

-- Source: lib://Executive Dashboard:DataFiles/InventoryBalances.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.INVENTORYBALANCES (
    LINE DESC 1                              VARCHAR(16777216),
    CLASSTURNS                               VARCHAR(16777216),
    THROUGHPUTQTY                            NUMBER(38,4),
    COSTPRICE                                NUMBER(38,4),
    STOCKOH                                  VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/ItemBranchMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.ITEMBRANCHMASTER (
    ITEM-BRANCH KEY                          VARCHAR(16777216),
    SHORT NAME                               VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/ItemMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.ITEMMASTER (
    PRODUCT GROUP                            VARCHAR(16777216),
    PRODUCT LINE                             VARCHAR(16777216),
    PRODUCT SUB GROUP                        VARCHAR(16777216),
    PRODUCT TYPE                             VARCHAR(16777216),
    SHORT NAME                               VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/ProductGroupMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.PRODUCTGROUPMASTER (
    PRODUCT GROUP                            VARCHAR(16777216),
    PRODUCT GROUP DESC                       VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/ProductSubGroupMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.PRODUCTSUBGROUPMASTER (
    PRODUCT SUB GROUP                        VARCHAR(16777216),
    PRODUCT SUB GROUP DESC                   VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/ProductTypeMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.PRODUCTTYPEMASTER (
    PRODUCT TYPE                             VARCHAR(16777216),
    PRODUCT TYPE DESC                        VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard:DataFiles/SalesRepMaster.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.SALESREPMASTER (
    SALES REP                                NUMBER(38,4),
    SALES REP NAME                           NUMBER(38,4)
);

-- Source: lib://Executive Dashboard Data/RegionalSales.xlsx  (flat file)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.REGIONALSALES (
    MONTHLYREGIONKEY                         VARCHAR(16777216),
    BUDGET AMOUNT                            NUMBER(38,4)
);

-- Source: lib://Executive Dashboard Data/ExpenseAccounts.xls  (flat file)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.EXPENSEACCOUNTS (
    ACCOUNT                                  VARCHAR(16777216),
    ACCOUNTDESC                              VARCHAR(16777216)
);

-- Source: lib://Executive Dashboard Data/Calendar.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.CALENDAR (
    FISCAL QUARTER                           VARCHAR(16777216),
    FISCAL YEAR                              VARCHAR(16777216),
    FISCALMONTH                              VARCHAR(16777216),
    FISCALMONTHNUM                           VARCHAR(16777216),
    FISCALROLLQT                             VARCHAR(16777216),
    YYYYMM                                   VARCHAR(16777216)
);

