///$tab Load From QVDs
SET ThousandSep=',';
SET DecimalSep='.';
SET MoneyThousandSep=',';
SET MoneyDecimalSep='.';
SET MoneyFormat='$#,##0.00;-$#,##0.00';
SET TimeFormat='h:mm:ss TT';
SET DateFormat='M/D/YYYY';
SET TimestampFormat='M/D/YYYY h:mm:ss[.fff] TT';
SET FirstWeekDay=6;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='en-US';
SET CreateSearchIndexOnReload=1;
SET MonthNames='Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec';
SET LongMonthNames='January;February;March;April;May;June;July;August;September;October;November;December';
SET DayNames='Mon;Tue;Wed;Thu;Fri;Sat;Sun';
SET LongDayNames='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';

LET vCurrentMonthNum = NUM(Month(Makedate(2024,3,1)));
LET vCurrentMonth = Month(Makedate(2024,3,1));
Let vCurrentYear = num(year(Makedate(2024,3,1)));


Let vTodaysDate = num(makedate(2024,3,1));
Let v12month = num(Makedate(2023,3,1));
Let vRolling12months = Num#($(v12month),'YYYYMM');

LET vOldDate = num(Makedate(2024,3,1));

LET vToday = (Makedate(2024,3,1));

LET vAdjDays = $(vTodaysDate) - $(vOldDate); //the gap between july 2003 and today

//SET vQVDPath = "Database\QVD\";

[AccountGroupMaster]:
   LOAD
    AccountGroup,
    AccountGroupDesc
FROM [lib://Executive Dashboard:DataFiles/AccountGroupMaster.qvd]
(qvd);


[AccountMaster]:
LOAD
    Account,
    AccountGroup
FROM [lib://Executive Dashboard:DataFiles/AccountMaster.qvd]
(qvd);

[Accounts]:
LOAD
    Account,
    AccountDesc
FROM [lib://Executive Dashboard:DataFiles/Accounts.qvd]
(qvd);

[ARSummary-1]:
LOAD
    CustKeyAR,
    ARAge,
    ARAgeBal
FROM [lib://Executive Dashboard:DataFiles/ARSummary-1.qvd]
(qvd);

[ARSummary]:
LOAD
    CustKeyAR,
    ARGross,
    AROpen,
    ARCurrent,
    "AR1-30",
    "AR31-60",
    "AR60+",
    ARCredit,
    ARSalesPerDay,
    ARAvgBal
FROM [lib://Executive Dashboard:DataFiles/ARSummary.qvd]
(qvd);

Budget:
LOAD
    MonthlyRegionKey,
    "Budget Amount"
FROM [lib://Executive Dashboard:DataFiles/Budget.qvd]
(qvd);

Calendar:
LOAD
    "Fiscal Quarter",
    FiscalMonthNum,
    "Fiscal Year",
    FiscalMonth,
    FiscalRollQt,
    YYYYMM
FROM [lib://DataFiles/Calendar_2024.qvd]
(qvd);


ChannelMaster:
LOAD
    Segment,
    SegmentDesc,
    SegmentGroup
FROM [lib://Executive Dashboard:DataFiles/ChannelMaster.qvd]
(qvd);

[CustomerAddressMaster]:
LOAD
    "Address Number",
    "Customer Address 1",
    "Zip Code"
FROM [lib://Executive Dashboard:DataFiles/CustomerAddressMaster.qvd]
(qvd);

CustomerMap:
LOAD
    CustKey,
    CustKeyAR
FROM [lib://Executive Dashboard:DataFiles/CustomerMap.qvd]
(qvd);

CustomerMaster:
LOAD
    "Address Number",
    "Business Family",
    Segment,
    Customer,
    "Customer Number",
    "Customer Type",
    "Distribution Channel Mgr",
    Division,
    Phone,
    "Region Code",
    "Regional Sales Mgr",
    "Zone Mgr",
    "Sales Rep"
FROM [lib://Executive Dashboard:DataFiles/CustomerMaster.qvd]
(qvd);

Expenses:
LOAD
    MonthlyRegionKey,
    Account,
    ExpenseActual,
    ExpenseBudget
FROM [lib://Executive Dashboard:DataFiles/Expenses.qvd]
(qvd);


[FactTable Init]:
LOAD
    MonthlyRegionKey,
    Region,
    "Address Number",
    CustKey,
    "Invoice Number",
    "Item-Branch Key",
    "Late Shipment",
    "Line Desc 1",
    "Open Order Amount",
    "Order Number",
    "Order Status", 
    Addmonths(OrderDate,9) as OrderDate,
    OrderID,
    OrderStat,
    Addmonths("Promised Delivery Date", 9) as "Promised Delivery Date",
    "Sales Amount",
    "Sales Cost Amount",
    "Sales Margin Amount",
    "Sales Price",
    "Sales Quantity",
    "Ship To",
    Addmonths(YYYYMM, 9) as YYYYMM
FROM [lib://Executive Dashboard:DataFiles/FactTable.qvd]
(qvd);

[FactTable]:
noconcatenate LOAD
    MonthlyRegionKey,
    Region,
    "Address Number",
    CustKey,
    "Invoice Number",
    "Item-Branch Key",
    "Late Shipment",
    "Line Desc 1",
    "Open Order Amount",
    "Order Number",
    "Order Status", 
    OrderDate,
    OrderID,
    OrderStat,
    "Promised Delivery Date",
    "Sales Amount",
    "Sales Cost Amount",
    "Sales Margin Amount",
    "Sales Price",
    "Sales Quantity",
    "Ship To",
    YYYYMM
resident [FactTable Init]
;

drop table [FactTable Init];

HistoryFlag:
LOAD
    Addmonths(YYYYMM,9) as YYYYMM, 
    _HistoryFlag
FROM [lib://Executive Dashboard:DataFiles/HistoryFlag.qvd]
(qvd);

[InventoryBalances]:
LOAD
    "Line Desc 1",
    ClassTurns,
    ThroughputQty,
    CostPrice,
    StockOH
FROM [lib://Executive Dashboard:DataFiles/InventoryBalances.qvd]
(qvd);

[ItemBranchMaster]:
LOAD
    "Item-Branch Key",
    "Short Name"
FROM [lib://Executive Dashboard:DataFiles/ItemBranchMaster.qvd]
(qvd);

ItemMaster:
LOAD
    "Product Group",
    "Product Line",
    "Product Sub Group",
    "Product Type",
    "Short Name"
FROM [lib://Executive Dashboard:DataFiles/ItemMaster.qvd]
(qvd);

ProductGroupMaster:
LOAD
    "Product Group",
    "Product Group Desc"
FROM [lib://Executive Dashboard:DataFiles/ProductGroupMaster.qvd]
(qvd);

ProductSubGroupMaster:
LOAD
    "Product Sub Group",
    "Product Sub Group Desc"
FROM [lib://Executive Dashboard:DataFiles/ProductSubGroupMaster.qvd]
(qvd);

ProductTypeMaster:
LOAD
    "Product Type",
    "Product Type Desc"
FROM [lib://Executive Dashboard:DataFiles/ProductTypeMaster.qvd]
(qvd);

SalesRepMaster:
LOAD
    "Sales Rep",
    "Sales Rep Name"
FROM [lib://Executive Dashboard:DataFiles/SalesRepMaster.qvd]
(qvd);

Exit Script;





///$tab Main
SET ThousandSep=',';
SET DecimalSep='.';
SET MoneyThousandSep=',';
SET MoneyDecimalSep='.';
SET MoneyFormat='$#,##0.00;($#,##0.00)';
SET TimeFormat='h:mm:ss TT';
SET DateFormat='M/D/YYYY';
SET TimestampFormat='M/D/YYYY h:mm:ss[.fff] TT';
SET MonthNames='Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec';
SET DayNames='Mon;Tue;Wed;Thu;Fri;Sat;Sun';

LET vCurrentMonthNum = NUM(Month(Makedate(2013,5,31)));
LET vCurrentMonth = Month(Makedate(2013,5,31));
Let vCurrentYear = num(year(Makedate(2013,5,31)));


Let vTodaysDate = num(makedate(2013,5,31));
Let v12month = num(Makedate(2012,5,31));
Let vRolling12months = Num#($(v12month),'YYYYMM');

LET vOldDate = num(Makedate(2013,5,31));

LET vToday = (Makedate(2013,5,31));

LET vAdjDays = $(vTodaysDate) - $(vOldDate); //the gap between july 2003 and today

SET vQVDPath = "Database\QVD\";

LOAD
    AccountGroup,
    AccountGroupDesc
FROM 'lib://Executive Dashboard Data/AccountGroupMaster.qvd'
(qvd);




///$tab Account
