"""Generate Snowflake landing-zone DDL for every external source.

Each QVD / file / SQL source becomes a CREATE TABLE in the RAW schema. Types
are inferred heuristically and clearly marked so a data engineer can refine
them against the real source metadata.
"""
from __future__ import annotations

from ..models import LoadKind, QvScript
from ..utils import case_identifier, sql_type_guess


def generate(script: QvScript, config: dict) -> str:
    tgt = config["target"]
    db = case_identifier(tgt["database"], tgt["identifier_case"])
    raw = case_identifier(tgt["raw_schema"], tgt["identifier_case"])
    case = tgt["identifier_case"]

    lines: list[str] = [
        "-- =====================================================================",
        f"-- Snowflake RAW landing DDL  (generated by qv2dbt from {script.name})",
        "-- Types are inferred heuristically - review against source metadata.",
        "-- =====================================================================",
        f"CREATE DATABASE IF NOT EXISTS {db};",
        f"CREATE SCHEMA IF NOT EXISTS {db}.{raw};",
        "",
    ]

    for src in script.sources:
        tbl = case_identifier(src.identifier, case)
        origin = {
            LoadKind.QVD: "QVD extract",
            LoadKind.FILE: "flat file",
            LoadKind.SQL: "source SQL SELECT",
        }.get(src.kind, "source")
        lines.append(f"-- Source: {src.locator}  ({origin})")
        lines.append(f"CREATE TABLE IF NOT EXISTS {db}.{raw}.{tbl} (")
        cols = src.fields or ["raw_record"]
        rendered = []
        for fld in cols:
            col = case_identifier(fld, case)
            rendered.append(f"    {col:<40} {sql_type_guess(fld)}")
        lines.append(",\n".join(rendered))
        lines.append(");")
        lines.append("")

    if not script.sources:
        lines.append("-- (No external QVD/file/SQL sources detected.)")

    return "\n".join(lines) + "\n"
