-- ================================================================
-- Snowflake views generated by qv2dbt from stress_test.qvs
-- Run top-to-bottom (already in dependency order).
-- ================================================================
create schema if not exists LUNDBECK_UKIE.STAGING;
create schema if not exists LUNDBECK_UKIE.MARTS;

-- Customers  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_CUSTOMERS as
select
    CustomerID,
    INITCAP(CustomerName) as CUSTOMERNAME,
    UPPER(TRIM(Email)) as EMAIL,
    coalesce((select MAPPED_VALUE from LUNDBECK_UKIE.STAGING.MAP_COUNTRY_MAP where MAPPED_KEY = CountryCode limit 1), 'N/A') as COUNTRY,
    LEFT(Phone, 3) as AREACODE,
    CASE WHEN CreditLimit IS NULL THEN 0 ELSE CreditLimit END as CREDITLIMIT,
    TO_DATE(SignupDate, 'YYYY-MM-DD') as SIGNUPDATE,
    DATEADD('YEAR', 1, SignupDate) as RENEWALDATE,
    SIGN(Balance) as BALANCESIGN
from LUNDBECK_UKIE.RAW.CUSTOMERS as base
where LENGTH(CustomerID) > 0
;

-- Orders  [intermediate]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.INT_ORDERS as
select *
from (select 
    OrderID,
    CustomerID,
    ProductID,
    TO_NUMBER(Quantity) as QUANTITY,
    TO_NUMBER(UnitPrice) * TO_NUMBER(Quantity) as GROSSAMOUNT,
    GREATEST(Discount1, Discount2) as MAXDISCOUNT,
    /* TODO review */ Peek('PrevOrder', -1, 'Orders') as PREVORDERREF,
    TO_DATE(OrderDate) as ORDERDATE,
    DATE_TRUNC('MONTH', OrderDate) as ORDERMONTH
from LUNDBECK_UKIE.RAW.ORDERS) as base
left join LUNDBECK_UKIE.STAGING.INT_ORDERS_JOIN3 as j1 using (CUSTOMERID)
;

-- Orders__join3  [intermediate]  (from QlikView 'resident')
create or replace view LUNDBECK_UKIE.STAGING.INT_ORDERS_JOIN3 as
select
    CustomerID,
    Country,
    CreditLimit
from LUNDBECK_UKIE.STAGING.STG_CUSTOMERS as base
;

-- sales_fact  [mart]  (from QlikView 'resident')
create or replace view LUNDBECK_UKIE.MARTS.MART_SALES_FACT as
select
    ProductID,
    Country,
    YEAR(OrderDate) as ORDERYEAR,
    MONTH(OrderDate) as ORDERMONTH,
    SUM(GrossAmount) as TOTALREVENUE,
    COUNT(OrderID) as ORDERCOUNT,
    AVG(GrossAmount) as AVGORDERVALUE,
    MEDIAN(GrossAmount) as MEDIANORDERVALUE
from LUNDBECK_UKIE.STAGING.INT_ORDERS as base
group by ProductID, Country, YEAR(OrderDate), MONTH(OrderDate)
;

