-- =====================================================================
-- Snowflake RAW landing DDL  (generated by qv2dbt from sales_pipeline.qvs)
-- Types are inferred heuristically - review against source metadata.
-- =====================================================================
CREATE DATABASE IF NOT EXISTS LUNDBECK_UKIE;
CREATE SCHEMA IF NOT EXISTS LUNDBECK_UKIE.RAW;

-- Source: lib://DataFiles/qvd/products.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.PRODUCTS (
    PRODUCTID                                VARCHAR(100),
    PRODUCTNAME                              VARCHAR(16777216),
    THERAPEUTICAREA                          VARCHAR(16777216),
    UNITPRICE                                NUMBER(38,4),
    ISDISCONTINUED                           VARCHAR(16777216)
);

-- Source: lib://DataFiles/csv/sales_2026.csv  (flat file)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.SALES_2026 (
    ORDERID                                  VARCHAR(100),
    PRODUCTID                                VARCHAR(100),
    CUSTOMERID                               VARCHAR(100),
    COUNTRYCODE                              VARCHAR(16777216),
    ORDERDATE                                DATE,
    QUANTITY                                 NUMBER(38,4),
    GROSSAMOUNT                              NUMBER(38,4),
    COUNTRY                                  VARCHAR(16777216),
    ORDERPREFIX                              VARCHAR(16777216)
);

-- Source: lib://DataFiles/qvd/sales_2025.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.SALES_2025 (
    ORDERID                                  VARCHAR(100),
    PRODUCTID                                VARCHAR(100),
    CUSTOMERID                               VARCHAR(100),
    COUNTRYCODE                              VARCHAR(16777216),
    ORDERDATE                                DATE,
    QUANTITY                                 NUMBER(38,4),
    GROSSAMOUNT                              NUMBER(38,4)
);

