-- =====================================================================
-- Snowflake RAW landing DDL  (generated by qv2dbt from stress_test.qvs)
-- Types are inferred heuristically - review against source metadata.
-- =====================================================================
CREATE DATABASE IF NOT EXISTS LUNDBECK_UKIE;
CREATE SCHEMA IF NOT EXISTS LUNDBECK_UKIE.RAW;

-- Source: lib://DW/qvd/customers.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.CUSTOMERS (
    CUSTOMERID                               VARCHAR(100),
    CUSTOMERNAME                             VARCHAR(16777216),
    EMAIL                                    VARCHAR(16777216),
    COUNTRY                                  VARCHAR(16777216),
    AREACODE                                 VARCHAR(16777216),
    CREDITLIMIT                              VARCHAR(16777216),
    SIGNUPDATE                               DATE,
    RENEWALDATE                              DATE,
    BALANCESIGN                              VARCHAR(16777216)
);

-- Source: lib://DW/qvd/orders.qvd  (QVD extract)
CREATE TABLE IF NOT EXISTS LUNDBECK_UKIE.RAW.ORDERS (
    ORDERID                                  VARCHAR(100),
    CUSTOMERID                               VARCHAR(100),
    PRODUCTID                                VARCHAR(100),
    QUANTITY                                 NUMBER(38,4),
    GROSSAMOUNT                              NUMBER(38,4),
    MAXDISCOUNT                              VARCHAR(16777216),
    PREVORDERREF                             VARCHAR(16777216),
    ORDERDATE                                DATE,
    ORDERMONTH                               VARCHAR(16777216)
);

