-- ================================================================
-- Snowflake views generated by qv2dbt from Executive Dashboard.qvs
-- Run top-to-bottom (already in dependency order).
-- ================================================================
create schema if not exists LUNDBECK_UKIE.STAGING;
create schema if not exists LUNDBECK_UKIE.MARTS;

-- AccountGroupMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_ACCOUNT_GROUP_MASTER as
select
    AccountGroup,
    AccountGroupDesc
from LUNDBECK_UKIE.RAW.ACCOUNTGROUPMASTER as base
;

-- AccountMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_ACCOUNT_MASTER as
select
    Account,
    AccountGroup
from LUNDBECK_UKIE.RAW.ACCOUNTMASTER as base
;

-- Accounts  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_ACCOUNTS as
select
    Account,
    AccountDesc
from LUNDBECK_UKIE.RAW.ACCOUNTS as base
;

-- ARSummary-1  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_ARSUMMARY_1 as
select
    CustKeyAR,
    ARAge,
    ARAgeBal
from LUNDBECK_UKIE.RAW.ARSUMMARY_1 as base
;

-- ARSummary  [mart]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.MARTS.MART_ARSUMMARY as
select
    CustKeyAR,
    ARGross,
    AROpen,
    ARCurrent,
    "AR1-30",
    "AR31-60",
    "AR60+",
    ARCredit,
    ARSalesPerDay,
    ARAvgBal
from LUNDBECK_UKIE.RAW.ARSUMMARY as base
;

-- Budget  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_BUDGET as
select
    MonthlyRegionKey,
    "Budget Amount"
from LUNDBECK_UKIE.RAW.BUDGET as base
;

-- Calendar  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_CALENDAR as
select
    "Fiscal Quarter",
    FiscalMonthNum,
    "Fiscal Year",
    FiscalMonth,
    FiscalRollQt,
    YYYYMM
from LUNDBECK_UKIE.RAW.CALENDAR_2024 as base
;

-- ChannelMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_CHANNEL_MASTER as
select
    Segment,
    SegmentDesc,
    SegmentGroup
from LUNDBECK_UKIE.RAW.CHANNELMASTER as base
;

-- CustomerAddressMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_CUSTOMER_ADDRESS_MASTER as
select
    "Address Number",
    "Customer Address 1",
    "Zip Code"
from LUNDBECK_UKIE.RAW.CUSTOMERADDRESSMASTER as base
;

-- CustomerMap  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_CUSTOMER_MAP as
select
    CustKey,
    CustKeyAR
from LUNDBECK_UKIE.RAW.CUSTOMERMAP as base
;

-- CustomerMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_CUSTOMER_MASTER as
select
    "Address Number",
    "Business Family",
    Segment,
    Customer,
    "Customer Number",
    "Customer Type",
    "Distribution Channel Mgr",
    Division,
    Phone,
    "Region Code",
    "Regional Sales Mgr",
    "Zone Mgr",
    "Sales Rep"
from LUNDBECK_UKIE.RAW.CUSTOMERMASTER as base
;

-- Expenses  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_EXPENSES as
select
    MonthlyRegionKey,
    Account,
    ExpenseActual,
    ExpenseBudget
from LUNDBECK_UKIE.RAW.EXPENSES as base
;

-- FactTable Init  [mart]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.MARTS.MART_FACT_TABLE_INIT as
select
    MonthlyRegionKey,
    Region,
    "Address Number",
    CustKey,
    "Invoice Number",
    "Item-Branch Key",
    "Late Shipment",
    "Line Desc 1",
    "Open Order Amount",
    "Order Number",
    "Order Status",
    DATEADD('MONTH', 9, OrderDate) as ORDERDATE,
    OrderID,
    OrderStat,
    DATEADD('MONTH', 9, "Promised Delivery Date") as PROMISED DELIVERY DATE,
    "Sales Amount",
    "Sales Cost Amount",
    "Sales Margin Amount",
    "Sales Price",
    "Sales Quantity",
    "Ship To",
    DATEADD('MONTH', 9, YYYYMM) as YYYYMM
from LUNDBECK_UKIE.RAW.FACTTABLE as base
;

-- FactTable  [mart]  (from QlikView 'resident')
create or replace view LUNDBECK_UKIE.MARTS.MART_FACT_TABLE as
select
    MonthlyRegionKey,
    Region,
    "Address Number",
    CustKey,
    "Invoice Number",
    "Item-Branch Key",
    "Late Shipment",
    "Line Desc 1",
    "Open Order Amount",
    "Order Number",
    "Order Status",
    OrderDate,
    OrderID,
    OrderStat,
    "Promised Delivery Date",
    "Sales Amount",
    "Sales Cost Amount",
    "Sales Margin Amount",
    "Sales Price",
    "Sales Quantity",
    "Ship To",
    YYYYMM
from LUNDBECK_UKIE.MARTS.MART_FACT_TABLE_INIT as base
;

-- HistoryFlag  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_HISTORY_FLAG as
select
    DATEADD('MONTH', 9, YYYYMM) as YYYYMM,
    _HistoryFlag
from LUNDBECK_UKIE.RAW.HISTORYFLAG as base
;

-- InventoryBalances  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_INVENTORY_BALANCES as
select
    "Line Desc 1",
    ClassTurns,
    ThroughputQty,
    CostPrice,
    StockOH
from LUNDBECK_UKIE.RAW.INVENTORYBALANCES as base
;

-- ItemBranchMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_ITEM_BRANCH_MASTER as
select
    "Item-Branch Key",
    "Short Name"
from LUNDBECK_UKIE.RAW.ITEMBRANCHMASTER as base
;

-- ItemMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_ITEM_MASTER as
select
    "Product Group",
    "Product Line",
    "Product Sub Group",
    "Product Type",
    "Short Name"
from LUNDBECK_UKIE.RAW.ITEMMASTER as base
;

-- ProductGroupMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_PRODUCT_GROUP_MASTER as
select
    "Product Group",
    "Product Group Desc"
from LUNDBECK_UKIE.RAW.PRODUCTGROUPMASTER as base
;

-- ProductSubGroupMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_PRODUCT_SUB_GROUP_MASTER as
select
    "Product Sub Group",
    "Product Sub Group Desc"
from LUNDBECK_UKIE.RAW.PRODUCTSUBGROUPMASTER as base
;

-- ProductTypeMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_PRODUCT_TYPE_MASTER as
select
    "Product Type",
    "Product Type Desc"
from LUNDBECK_UKIE.RAW.PRODUCTTYPEMASTER as base
;

-- SalesRepMaster  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_SALES_REP_MASTER as
select
    "Sales Rep",
    "Sales Rep Name"
from LUNDBECK_UKIE.RAW.SALESREPMASTER as base
;

-- table_23  [staging]  (from QlikView 'qvd')
create or replace view LUNDBECK_UKIE.STAGING.STG_TABLE_23 as
select
    AccountGroup,
    AccountGroupDesc
from LUNDBECK_UKIE.RAW.ACCOUNTGROUPMASTER as base
;

